# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_0axyzmnU9Hc89TYr9IxQ7HnxUiz4L2
"""

# Step 1: Import Libraries

import pandas as pd
import numpy as np

#  Step 2: Load Dataset

df=pd.read_csv("/content/Mall_Customers.csv")

# Display first 5 rows
print(df.head())

#  Step 3: Data Understanding

# Check dataset info (data types, null values)
print(df.info())

# Summary statistics
print(df.describe())

# Check missing values
print(df.isnull().sum())

#  Step 4: Data Preprocessing

# Convert categorical data (Gender) into numeric
df['Genre']=df['Genre'].map({'Male':0,'Female':1})

# Select relevant features for clustering
X=df[['Age','Annual Income (k$)','Spending Score (1-100)']]


# Preview selected data
print(X.head())

# Step 5: Elbow Method (Optimal clusters)
# 1. Required library import karo

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Elbow Method
inertia=[]

# Test cluster sizes from 1 to 10
for K in range(1,11):
  kmeans=KMeans(n_clusters=K,random_state=42)
  kmeans.fit(X)
  inertia.append(kmeans.inertia_)


# Plot Elbow Graph
plt.figure(figsize=(8,5))
plt.plot(range(1, 11), inertia, marker='o')
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.show()

# Step 6: Apply KMeans Clustering

# Choose optimal clusters (k = 4 based on elbow method)
k = 4
kmeans = KMeans(n_clusters=k, random_state=42)
y_kmeans = kmeans.fit_predict(X)

# add cluster column
df['Cluster'] = y_kmeans


# Display updated dataset
print(df.head())

# Step 7: Visualization of Clusters
plt.scatter(df['Annual Income (k$)'], df['Spending Score (1-100)'],
            c=df['Cluster'], cmap='viridis')
plt.xlabel('Income')
plt.ylabel('Spending Score')
plt.title('Customer Segments')
plt.show()

# Step 8: Cluster Analysis

# Check average values for each cluster
df.groupby('Cluster').mean()



